apiVersion: v1
kind: ConfigMap
metadata:
  name: eck-ui-versions
  labels:
    {{- include "eck-ui.labels" . | nindent 4 }}
    app.kubernetes.io/component: versions
data:
  versions.json: |
    {
      "defaultVersion": {{ (index .Values.versions.list 0) | quote }},
      "versions": [
        {{- $last := sub (len .Values.versions.list) 1 }}
        {{- range $i, $v := .Values.versions.list }}
        {{ $v | quote }}{{ if ne $i $last }},{{ end }}
        {{- end }}
      ]
    }
