apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eck-ui

resources:
  - all-in-one.yaml

commonLabels:
  app.kubernetes.io/part-of: eck-ui

images:
  - name: eck-ui
    newTag: latest
